### ISSUE TITLE
feat: need maximum windows

### ISSUE THREAD

**Issue by konosubakonoakua** [maliknajjar/guifier#3]
![image](https://github.com/user-attachments/assets/65b8ca60-58be-4386-82ae-2dd3e6f7e693)
Dear author, I cannot see all the parts when nesting is deep

**Comment by maliknajjar** [comment]
Hi @konosubakonoakua, Thanks for using the library
what do you suggest as a solution to this issue?

**Comment by maliknajjar** [comment]
maybe we can add a min-width and let the user scroll horizontally to see the remaining content.
wdyt?

**Comment by konosubakonoakua** [comment]
> maybe we can add a min-width and let the user scroll horizontally to see the remaining content. wdyt?

yes, this is a solution. maybe a toggle and fullscreen switch would be nice :)

**Comment by maliknajjar** [comment]
I think this is more related to the guifier.com web app than to the guifier library itself.
I will change the the webapp and maybe add a button that expands the guifier UI view.

**Comment by maliknajjar** [comment]
can you please send us that exact toml text here. so that I can test with it?

**Comment by konosubakonoakua** [comment]
> can you please send us that exact toml text here. so that I can test with it?

sorry，I can't upload that :/

**Comment by maliknajjar** [comment]
np .. I will work on it and inform you asap

**Comment by maliknajjar** [comment]
there you go .. you have the full screen button now
![image](https://github.com/user-attachments/assets/66f0bc84-d1aa-407c-ae3e-f39ca391dffa)
and for people who are integrating guifier in their apps you can enable it from here
![image](https://github.com/user-attachments/assets/6eb9d801-4dc7-4f93-a295-ccc7b5da8c65)
there is a new property called fullScreen

**Comment by maliknajjar** [comment]
let me know if that fixed your issue
