### ISSUE TITLE
TOML local date not supported

### ISSUE THREAD

**Issue by MoritzRitter** [maliknajjar/guifier#5]
Acc. to https://toml.io/en/v1.0.0#local-date a local date looks like this:
`ld1 = 1979-05-27`

However, the TOML Viewer & Editor at https://guifier.com/toml reports an error
`Error: SyntaxError: Expected "T" but "\n" found.`

Expected behavior: the local date is shown and can be edited.

**Comment by maliknajjar** [comment]
Hi @MoritzRitter
Thank you for helping finding these issues and bugs. really appreciate it

this should be an issue in the toml parser library we are using.
I have to debug it and see exactly whats the cause of this issue.
I will inform asap

**Comment by maliknajjar** [comment]
The issue arises because the [toml](https://www.npmjs.com/package/toml) package on npm is no longer maintained and only supports TOML specification version 0.4.0, which is outdated.
I will try to find an alternative library and replace it.

**Comment by maliknajjar** [comment]
Hi @MoritzRitter,  
I've replaced the TOML library with `smol-toml`, which supports TOML v1.0.0. Additionally, I've implemented a `Date` field type, allowing the TOML string to be rendered as a date input.

![image](https://github.com/user-attachments/assets/5d1645a7-168f-49cd-b099-ac03b331e764)

You can check it out here:  
https://guifier.com/toml/  

It now successfully parses the toml date values.

**Comment by MoritzRitter** [comment]
Thanks for the update! There seems to be still be a little flaw:

When I open the page, everything is fine:
![image](https://github.com/user-attachments/assets/1255603d-1c15-40f3-8061-7a201a746b4e)

But then, when I edit the date using the widget, the date is written back as string (instead of a local date):
![image](https://github.com/user-attachments/assets/24250ef7-f1d5-4c42-8be1-ee2f72cfe8a7)
Expected: the local date `date = 1979-05-28` (without the string quotes `""`).

**Comment by maliknajjar** [comment]
I will check that asap

**Comment by maliknajjar** [comment]
Currently, when editing the date, it gets parsed into this format:

![image](https://github.com/user-attachments/assets/07591048-e65c-465e-a4cd-04e6ea85fe09) 

The [smol-toml](https://github.com/squirrelchat/smol-toml) library includes the time by default when handling dates. Based on their documentation, I couldn’t find a way to adjust the parsing behavior to output this specific date format:  

![image](https://github.com/user-attachments/assets/65642b7d-f02f-476d-b1eb-3f106df868c1)  

Does this work for you?

**Comment by MoritzRitter** [comment]
Thanks for checking! Let's put it like this: I would need a local date without timezone info etc. And this is not what we have at the moment. But I can work around it. Much better than a parsing error!

**Comment by maliknajjar** [comment]
Got it! Since this is related to the smol-toml library, I’ve opened an [issue](https://github.com/squirrelchat/smol-toml/issues/28) in their repository. Hopefully, they already have this feature or are willing to implement it.

**Comment by maliknajjar** [comment]
Hi @MoritzRitter I fixed the issue
now it works as expected even if the date is edited from the UI
![image](https://github.com/user-attachments/assets/3bc9f310-2b13-4ba4-85c4-00b5cbb59e49)

**Comment by MoritzRitter** [comment]
Hi @maliknajjar Thanks for the update. There seems to be a new problem with the preservation of multi-line basic strings (acc. to https://toml.io/en/v1.0.0#string):
When I add such a string like in this example:
![image](https://github.com/user-attachments/assets/2bf0c104-3673-4ab4-b29e-bcfd070983e5)
then it is already now displayed in the widget omitting the new lines.
And when I then edit the date (or any other object) using the widgets on the right, then the string is converted to a basic string:
![image](https://github.com/user-attachments/assets/98a8df91-ad76-4706-8f55-b25f69ef3265)
While the content is probably still the same, this seems not to be the behavior that the user wants. Would you agree?

**Comment by maliknajjar** [comment]
Hi @MoritzRitter, I created a seperate issue for this https://github.com/maliknajjar/guifier/issues/7
you can follow it there
